[package]
name = "raw"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"

[dependencies]
rd-interface = { path = "../../rabbit-digger/rd-interface/", version = "0.4" }
# rd-interface = "0.3"
serde_derive = "1.0"
serde = "1.0"
tracing = "0.1.26"
tokio-smoltcp = "0.1.13"
smoltcp = "0.7"
tokio = { version = "1.5.0", features = ["rt", "macros", "net"] }
pcap = "0.8.1"
futures = "0.3"
lru_time_cache = "0.11"
parking_lot = "0.11.1"

[dependencies.tun-crate]
version = "0.5.1"
git = "https://github.com/meh/rust-tun.git"
rev = "19906c006512acf805f392e744e38aec8adc6618"
package = "tun"
features = ["async"]
